### ISSUE TITLE
환경 변수 설정

### ISSUE THREAD

**Issue by juhui88** [Team-Shaka/Breifing-WEB#16]
env 파일에 REACT_APP_BASE_URL로 서버 주소 넣어두었습니다
vercel에 환경변수 추가 부탁드립니다~

**Comment by Dawon00** [comment]
![image](https://github.com/Team-Shaka/Breifing-WEB/assets/71630722/9448d966-9e6a-4996-b223-9466f19bf34e)
설정 완료했습니다.
